var BlogEles = {
    nodes: [
        { data: { id: '1', name: 'Of Property', href: 'http://inhabitingtheanthropocene.com/2015/02/16/of-property/', color: '#86B342', weight:60 } },
        { data: { id: '2', name: 'Comment 1 on "Of Property"', href: 'http://inhabitingtheanthropocene.com/2015/02/16/of-property/comment-page-1/#comment-569', color: '#6FB1FC', weight:30 } },
        { data: { id: '3', name: 'Reply to Comment 1 on "Of Property"', href: 'http://inhabitingtheanthropocene.com/2015/02/16/of-property/comment-page-1/#comment-570', color: '#6FB1FC', weight:30 } },
        { data: { id: '4', name: 'Organisms as Ecosystem Engineers', href: 'http://inhabitingtheanthropocene.com/2015/02/19/organisms-as-ecosystem-engineers/', color: '#86B342', weight:60 } },
        { data: { id: '5', name: 'Comment 2 on "Of Property"', href: 'http://inhabitingtheanthropocene.com/2015/02/16/of-property/comment-page-1/#comment-576', color: '#6FB1FC', weight:30 } },
        { data: { id: '6', name: 'Comment 1 on "Organisms as Ecosystem Engineers"', href: 'http://inhabitingtheanthropocene.com/2015/02/19/organisms-as-ecosystem-engineers/comment-page-1/#comment-587', color: '#6FB1FC', weight:30 } },
        { data: { id: '7', name: 'Reply 1 to Comment 2 on "Of Property"', href: 'http://inhabitingtheanthropocene.com/2015/02/16/of-property/comment-page-1/#comment-592', color: '#6FB1FC', weight:30 } },
        { data: { id: '8', name: 'Comment 2 on "Organisms as Ecosystem Engineers"', href: 'http://inhabitingtheanthropocene.com/2015/02/19/organisms-as-ecosystem-engineers/comment-page-1/#comment-590', color: '#6FB1FC', weight:30 } },
        { data: { id: '9', name: 'Reply 1 to Comment 1 on "Organisms as Ecosystem Engineers"', href: 'http://inhabitingtheanthropocene.com/2015/02/19/organisms-as-ecosystem-engineers/comment-page-1/#comment-598', color: '#6FB1FC', weight:30 } },
        { data: { id: '10', name: 'Comment 3 on "Organisms as Ecosystem Engineers"', href: 'http://inhabitingtheanthropocene.com/2015/02/19/organisms-as-ecosystem-engineers/comment-page-1/#comment-594', color: '#6FB1FC', weight:30 } },
        { data: { id: '11', name: 'Comment 4 on "Organisms as Ecosystem Engineers"', href: 'http://inhabitingtheanthropocene.com/2015/02/19/organisms-as-ecosystem-engineers/comment-page-1/#comment-597', color: '#6FB1FC', weight:30 } },
        { data: { id: '12', name: 'Reply 1 to Comment 2 on "Organisms as Ecosystem Engineers"', href: 'http://inhabitingtheanthropocene.com/2015/02/19/organisms-as-ecosystem-engineers/comment-page-1/#comment-599', color: '#6FB1FC', weight:30 } },
        { data: { id: '13', name: '"Diachronous Beginnings of the Anthropocene: The Lower Bounding Surface of Anthropogenic Deposits"', href: 'http://inhabitingtheanthropocene.com/2015/02/23/diachronous-beginnings-of-the-anthropocene-the-lower-bounding-surface-of-anthropogenic-deposits/', color: '#86B342', weight:60 } },
        { data: { id: '14', name: 'Building "Equitable" Urban Resilience: The Challenge for Cities', href: 'http://inhabitingtheanthropocene.com/category/social-media-in-the-anthropocene/page/3/', color: '#86B342', weight:60 } },
        { data: { id: '15', name: 'Comment 1 on "Diachronous Beginnings of the Anthropocene: The Lower Bounding Surface of Anthropogenic Deposits"', href: 'http://inhabitingtheanthropocene.com/2015/02/23/diachronous-beginnings-of-the-anthropocene-the-lower-bounding-surface-of-anthropogenic-deposits/comment-page-1/#comment-610', color: '#6FB1FC', weight:30 } },
        { data: { id: '16', name: 'Comment 2 on "Diachronous Beginnings of the Anthropocene: The Lower Bounding Surface of Anthropogenic Deposits"', href: 'http://inhabitingtheanthropocene.com/2015/02/23/diachronous-beginnings-of-the-anthropocene-the-lower-bounding-surface-of-anthropogenic-deposits/comment-page-1/#comment-613', color: '#6FB1FC', weight:30 } },
        { data: { id: '17', name: 'Principles of Tsawalk: An Indigenous Approach to Global Crisis', href: 'http://inhabitingtheanthropocene.com/2015/03/02/principles-of-tsawalk-an-indigenous-approach-to-global-crisis/', color: '#86B342', weight:60 } },
        { data: { id: '18', name: '"Loess: The Yellow Earth"', href: 'http://inhabitingtheanthropocene.com/2015/03/05/loess-the-yellow-earth/', color: '#86B342', weight:60 } },
        { data: { id: '19', name: 'Comment 1 on "Building Equitable Urban Resilience: The Challenge for Cities"', href: 'http://inhabitingtheanthropocene.com/2015/02/25/building-equitable-urban-resilience/comment-page-1/#comment-621', color: '#6FB1FC', weight:30 } },
        { data: { id: '20', name: 'Reply 1 to Comment 1 on "Building Equitable Urban Resilience: The Challenge for Cities"', href: 'http://inhabitingtheanthropocene.com/2015/02/25/building-equitable-urban-resilience/comment-page-1/#comment-622', color: '#6FB1FC', weight:30 } },
        { data: { id: '21', name: 'Comment 1 on "Principles of Tsawalk: An Indigenous Approach to Global Crisis"', href: 'http://inhabitingtheanthropocene.com/2015/03/02/principles-of-tsawalk-an-indigenous-approach-to-global-crisis/#comments', color: '#6FB1FC', weight:30 } },
        { data: { id: '22', name: '"Concluding Remarks" on Animal Ecology and Demography', href: 'http://inhabitingtheanthropocene.com/2015/03/09/hutchinson-concluding-remarks/', color: '#86B342', weight:60 } },
        { data: { id: '23', name: '"A Safe Operating Space for Humanity"', href: 'http://inhabitingtheanthropocene.com/2015/03/14/a-safe-operating-space-for-humanity/', color: '#86B342', weight:60 } },
        { data: { id: '24', name: 'Comment 1 on "A Safe Operating Space for Humanity"', href: 'http://inhabitingtheanthropocene.com/2015/03/14/a-safe-operating-space-for-humanity/comment-page-1/#comment-642', color: '#6FB1FC', weight:30 } },
        { data: { id: '25', name: 'Toward an Ethics of Niche Construction', href: 'http://inhabitingtheanthropocene.com/2015/03/17/toward-an-ethics-of-niche-construction/', color: '#86B342', weight:60 } },
        { data: { id: '26', name: 'Implications of Manufacturing Habitability', href: 'http://inhabitingtheanthropocene.com/2015/03/20/implications-of-manufacturing-habitability/', color: '#86B342', weight:60 } },
        { data: { id: '27', name: 'Advancing Equity and Going Beyond Basic Survival', href: 'http://inhabitingtheanthropocene.com/2015/03/23/advancing-equity-and-going-beyond-basic-survival/', color: '#86B342', weight:60 } },
        { data: { id: '28', name: 'Memes as a Dimension of the Human Niche', href: 'http://inhabitingtheanthropocene.com/2015/03/27/memes-as-a-dimension-of-the-human-niche/', color: '#86B342', weight:60 } },
        { data: { id: '29', name: "Habitability's Non-Inevitability", href: 'http://inhabitingtheanthropocene.com/2015/03/31/habitabilitys-non-inevitability/', color: '#86B342', weight:60 } },
        { data: { id: '30', name: 'Comment 1 on Habitability\'s Non-Inevitability', href: 'http://inhabitingtheanthropocene.com/2015/03/31/habitabilitys-non-inevitability/comment-page-1/#comment-686', color: '#6FB1FC', weight:30 } },
        { data: { id: '31', name: 'Habitability as a commons: Fearing a tragedy of human(ized) nature', href: 'http://inhabitingtheanthropocene.com/2015/04/04/habitability-as-commons/', color: '#86B342', weight:60 } },
        { data: { id: '32', name: 'Toward a More Than Human Anthropocene', href: 'http://inhabitingtheanthropocene.com/2015/04/08/toward-a-more-than-human-anthropocene/', color: '#86B342', weight:60 } },
        { data: { id: '33', name: 'Comment 1 on Toward a More Than Human Anthropocene', href: 'http://inhabitingtheanthropocene.com/2015/04/08/toward-a-more-than-human-anthropocene/comment-page-1/#comment-721', color: '#6FB1FC', weight:30 } },
        { data: { id: '34', name: 'Reply 1 to Comment 1 on Toward a More Than Human Anthropocene', href: 'http://inhabitingtheanthropocene.com/2015/04/08/toward-a-more-than-human-anthropocene/comment-page-1/#comment-725', color: '#6FB1FC', weight:30 } },       
        { data: { id: '35', name: 'Reply 2 to Comment 1 on Toward a More Than Human Anthropocene', href: 'http://inhabitingtheanthropocene.com/2015/04/08/toward-a-more-than-human-anthropocene/comment-page-1/#comment-726', color: '#6FB1FC', weight:30 } },
        { data: { id: '36', name: 'The Dust of Civilization', href: 'http://inhabitingtheanthropocene.com/2015/04/11/the-dust-of-civilization/', color: '#86B342', weight:60 } }
    ],
    edges: [
        { data: { source: '1', target: '32', AuthColor: 'red', Arrow: 'none' } },
        { data: { source: '18', target: '1', AuthColor: 'red', Arrow: 'triangle' } },
        { data: { source: '25', target: '27', AuthColor: 'red', Arrow: 'none' } },
        { data: { source: '25', target: '28', AuthColor: 'red', Arrow: 'triangle' } },
        { data: { source: '31', target: '36', AuthColor: 'red', Arrow: 'triangle' } },
        { data: { source: '4', target: '22', AuthColor: 'green', Arrow: 'triangle' } },
        { data: { source: '26', target: '31', AuthColor: 'green', Arrow: 'triangle' } },
        { data: { source: '4', target: '18', AuthColor: 'green', Arrow: 'none' } },
        { data: { source: '25', target: '22', AuthColor: 'green', Arrow: 'none' } },
        { data: { source: '23', target: '25', AuthColor: 'magenta', Arrow: 'triangle' } },
        { data: { source: '31', target: '14', AuthColor: 'magenta', Arrow: 'none' } },
        { data: { source: '18', target: '23', AuthColor: 'orange', Arrow: 'triangle' } },
        { data: { source: '36', target: '13', AuthColor: 'orange', Arrow: 'none' } },
        { data: { source: '4', target: '18', AuthColor: 'orange', Arrow: 'triangle' } },
 
        //comments
        { data: { source: '2', target: '1', AuthColor: 'blue', Arrow: 'triangle' } },
        { data: { source: '3', target: '2', AuthColor: 'blue', Arrow: 'triangle' } },
        { data: { source: '7', target: '5', AuthColor: 'blue', Arrow: 'triangle' } },
        { data: { source: '9', target: '6', AuthColor: 'blue', Arrow: 'triangle' } },
        { data: { source: '12', target: '8', AuthColor: 'blue', Arrow: 'triangle' } },
        { data: { source: '20', target: '19', AuthColor: 'blue', Arrow: 'triangle' } },
        { data: { source: '5', target: '1', AuthColor: 'blue', Arrow: 'triangle' } },
        { data: { source: '6', target: '4', AuthColor: 'blue', Arrow: 'triangle' } },
        { data: { source: '8', target: '4', AuthColor: 'blue', Arrow: 'triangle' } },
        { data: { source: '10', target: '4', AuthColor: 'blue', Arrow: 'triangle' } },
        { data: { source: '11', target: '4', AuthColor: 'blue', Arrow: 'triangle' } },
        { data: { source: '15', target: '13', AuthColor: 'blue', Arrow: 'triangle' } },
        { data: { source: '16', target: '13', AuthColor: 'blue', Arrow: 'triangle' } },
        { data: { source: '19', target: '14', AuthColor: 'blue', Arrow: 'triangle' } },
        { data: { source: '21', target: '17', AuthColor: 'blue', Arrow: 'triangle' } },
        { data: { source: '24', target: '23', AuthColor: 'blue', Arrow: 'triangle' } },
        { data: { source: '30', target: '29', AuthColor: 'blue', Arrow: 'triangle' } },
        { data: { source: '34', target: '33', AuthColor: 'blue', Arrow: 'triangle' } },
        { data: { source: '33', target: '32', AuthColor: 'blue', Arrow: 'triangle' } },
        { data: { source: '35', target: '33', AuthColor: 'blue', Arrow: 'triangle' } }
    ]
}